### ISSUE TITLE
PyRDF.use("spark") hangs in SWAN

### ISSUE THREAD

**Issue by JavierCVilla** [vepadulano/PyRDF#1]
In a SWAN notebook, `PyRDF.use("spark")` freezes a notebook cell when there is no `SparkContext` preloaded, i.e. the connection with a Spark cluster has not been previously established.

**Comment by vepadulano** [comment]
This shouldn't happen at all, PyRDF.use("spark") invokes pyspark code that should also run on a single node. I tested it today on SWAN and it doesn't hang, so closing this one
