### ISSUE TITLE
Wrong import of backend modules in Python 3.7

### ISSUE THREAD

**Issue by vepadulano** [vepadulano/PyRDF#20]
In `__init__.py` all backend modules are being imported with absolute notation, e.g. `from backend import Utils`. The implicit relative path behaviour is allowed in Python 2.7, but doesn't work in Python 3.7, as documented [here](https://docs.python.org/3/tutorial/modules.html#intra-package-references). In the newer version of Python implicit imports use the dot notation to indicate the current and parent packages involved in the relative import. So the right way to do it would be `from .backend import Utils`.

**Comment by JavierCVilla** [comment]
Very nice catch @vepadulano 

I think we have only two possible solutions:

- Use explicit relative imports (supported by Python 2 and 3)
- Use absolute import everywhere (also supported by both versions)

Absolute paths are recommended by [PEP8](https://www.python.org/dev/peps/pep-0008/#imports), as they are usually more readable and tend to be better behaved. I think we should go for this one.

**Comment by vepadulano** [comment]
Fixed by #21
