### ISSUE TITLE
Long integers raises a syntax error in Python 3

### ISSUE THREAD

**Issue by vepadulano** [vepadulano/PyRDF#22]
```     
File "/home/PyRDF/tests/unit/backend/test_dist.py", line 163
ranges_reqd = [(0L, 10L)]
                      ^
SyntaxError: invalid syntax
```

In Python 3, all integers have "unlimited" precision, as documented [here](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex). As a consequence, a declaration such as `a = 1L` raises a `SyntaxError: invalid syntax`, as discussed [here](https://stackoverflow.com/questions/24249519/long-int-literal-invalid-syntax). Depending on how crucial these declarations are, the `L` symbol could be deleted to ensure compatibility with both versions of Python. Otherwise, we could add some feature detection in order to differentiate the code according to the Python version used, as suggested [here](https://docs.python.org/2/howto/pyporting.html#use-feature-detection-instead-of-version-detection).

**Comment by JavierCVilla** [comment]
Fixed by #24
