### ISSUE TITLE
Add FriendTree capabilities to distributed execution

### ISSUE THREAD

**Issue by vepadulano** [vepadulano/PyRDF#48]
The distributed execution of the DAG starts by calling ROOT RDataFrame with the arguments passed by the user to PyRDF.RDataFrame. 

If the TTree/TChain passed has some friend trees inside, the links to those other files will be lost since the Spark executor will only know about the location of the main TTree/TChain .root file(s). 

It is needed to add some friend tree checks in the distributed backend mapper function.

**Comment by JavierCVilla** [comment]
Added in #49
