### ISSUE TITLE
Add back AsNumpy tutorials for Spark

### ISSUE THREAD

**Issue by JavierCVilla** [vepadulano/PyRDF#79]
Revert [this commit](https://github.com/JavierCVilla/PyRDF/pull/78/commits/e899f866e8bd3585b9c8c15efc3a7052795ad7bd) once PyROOT has been properly modified to support the serialization of the `ndarray` wrapper class.

**Comment by vepadulano** [comment]
The CI job runs in a conda environment with ROOT 6.16. Even when the anaconda package will be updated to 6.18 it won't have the new `AsNumpy` changes, unless they make into the 6.18-patches at some point

**Comment by JavierCVilla** [comment]
@vepadulano Does ROOT-6.18.02/04 include the required changes?

**Comment by vepadulano** [comment]
When PyRDF will be included in ROOT these tutorials will be included in the ROOT tutorials
