### ISSUE TITLE
Wrong graph pruning in Python3.7

### ISSUE THREAD

**Issue by JavierCVilla** [vepadulano/PyRDF#8]
With `python-3.7.2` the `graph_prune` function removes nodes that should not be pruned. As a result, the following code does not work:

```python
import PyRDF
d = PyRDF.RDataFrame(1)
h = d.Histo1D("rdfentry_")
h.Draw()
```
Same code works for `python-2.7.15`.

**Comment by vepadulano** [comment]
solved by #28
